name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Tests with Coverage
        run: go test ./... -cover

  style:
    name: Lint & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run Formatting Check
        run: test -z "$(go fmt ./...)"

      - name: Install & Run Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

      - name: Install & Run gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest && gosec ./...

  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: [tests, style]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-451808

      - name: Build & Push Docker Image
        env:
          IMAGE_TAG: us-central1-docker.pkg.dev/notely-451808/notely-ar-repo/notely:${{ github.sha }}
        run: |
          gcloud builds submit --tag $IMAGE_TAG .
          gcloud container images add-tag $IMAGE_TAG us-central1-docker.pkg.dev/notely-451808/notely-ar-repo/notely:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-451808/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-451808 \
            --max-instances=4